<h1>Import Logs</h1>
<p>Click the link below to process all log entries at S3:</p>
<p>IMPORTANT: Clicking the link below will process logs, then permanently delete them from S3!</p>
<p>
    <?php foreach ($buckets as $bucket) : ?>
        <a class="btn btn-success" href="<?php echo $this->url('logs-process') . "/" . $bucket; ?>" title="Process <?php echo $bucket; ?> Logs Manually">Process <?php echo $bucket; ?> Logs Manually</a><br>
    <?php endforeach; ?>
</p>
